apiVersion: v1
kind: Pod
metadata:
  name: pod-example
spec:
  containers:
  - image: hons82/reverseproxy
    name: reverseproxy
    imagePullPolicy: Always          
    resources:
      requests:
        memory: "32Mi"
        cpu: "50m"
      limits:
        memory: "256Mi"
        cpu: "100m"
    ports:
    - containerPort: 8080
  restartPolicy: Always